#+ endpoint: http://labo-vm-2.v202.abes.fr:7200/repositories/men-habilitations-v5-inference-legal-base

PREFIX mov: <http://www.abes.fr/vocabularies/movies#>

SELECT DISTINCT * WHERE {
	?habilitation a mov:Habilitation;
		mov:from [mov:codeEtabid ?codeEtab];
		mov:start ?start;
		mov:end ?end.

	OPTIONAL {
		?habilitation mov:legalBase ?doc
	}

	FILTER(?codeEtab=?_code_etab)
}
